[project]
name = "StudySpark"
version = "1.0.0"
description = "blank"
requires-python = ">=3.11, <3.13"
dependencies = [
    "google-genai>=1.0.0",
    "streamlit>=1.40.0",
    "python-dotenv>=1.0.0",
    "langfuse>=2.0.0",
    "pypdf>=6.0.0"
]
packages = [{ include = "StudySpark" }]
